Here we demonstrate a method for evaluating music content analysis tools without relying on ground truths. While our objective here has been to formalize and demonstrate this method, we begin our discussion with consideration of the question results.

## Between-Tool Feature Variability

Tool comparison is a useful approach to examine the relative performance. It can provide a benchmark to improve upon, and allows for selecting an optimal tool for a given task. While each individual tool may be tested during it's development, independent or third-party tests on different data sets can help support the utility, accuracy or robustness of the tool. To this end, we applied our Version Variability Analysis predictions to this between-tool evaluation. Of particular interest here are the invariant features since we do not have a specific prediction about the degree of variability desired in variant features. Specifically, adopting an approach of minimizing variability between versions for invariant features is a useful benchmark. We find no differences in the variability between tools for the number of onsets, suggesting these three tools perform similarly, regardless of their accuracy or overall consistency. However, in respect to relative mode, we find that Librosa is the least variable option of the three tools examined. Since the primary difference between these three relative mode extractions is the method of chroma feature extraction, this likely means Librosa is least susceptible to pitch independent factors, such as timbre, despite being no less sensitive to timbre in spectral centroid evaluations.

## Comparing Variability Between Features

A key assumption of this method is the distinction between variant and invariant features. By comparing the different features to one another, we are able test that assumption: here we compared the features to one another within each tool. Both Librosa and MIRtoolbox support this assumption: invariant features are less variable than variant features. However, in respect to Essentia, relative mode is not significantly different from tempo (although it is significantly different from spectral centroid). When comparing the invariant features, relative mode is only less variable in the case of Librosa, with number of onsets consistently having the lowest ratios observed across all tools and features. This suggests that despite some variability being expected in the number of onsets due to ornamentation, relative mode is still susceptible to greater unwanted variability than number of onsets.

## Mediating Effects

We present two mediating effects that might influence the extraction of these features: instrument, and nominal mode. While these are by no means exhaustive, they are an effective example. Both these features do not significantly change the variability of any of the feature/tool combinations. While we would not expect the performed instrument to influence the invariant features, it seems more likely that the performed instrument would influence the variant features: specifically spectral centroid as a measure of timbre. However, since we compare the versions within a piece to the entire corpus, the variability between specific tracks on an album likely have the same degree of variability as all tracks on all albums, explaining the lack of difference here. Further, in the case of tempo, there is no reason to believe the instrument a performer selects would have an impact on their tempo choices in any systematic fashion. Applying these analyses to other factors, such as structural features of the pieces, may account for the variability seen in the other two questions.

## Version Variability Analysis

Beyond the specific results of the three questions considered above, Version Variability Analysis is a viable alternative to conventional accuracy evaluations. Specific applications include:

-   Tool/Algorithm Selection: As described above, selection of invariant feature extraction tools can be facilitated by minimizing the variability ratio. For instance, the minimal variability relative mode algorithm in this study would be Librosa. This approach can also be applied to parameter optimization: for instance, in the case of relative mode, this procedure could be applied to selecting optimal weights in the Krumhansl Schmuckler keyfinding algorithm. In the case of variant features, while not explored here, prior distributions from similar musical samples can be used as a variability target (in the case of this sample Palmers analysis of tempi in the WTC may be appropriate [@bach_well-tempered_2004])

-   Development and Testing: Applying a priori expectations of how features behave psychologically during development of music content analysis tools would improve these tools at the source. In conjunction with traditional accuracy assessments, this method may aid in identifying the factors that contribute to unwanted variability at a lower level in the processing chain. For instance, if the method by which chroma features are computed in a relative mode algorithm is highly variable, this can be diagnosed and localized with this method.

## Limitations

Ornamentation, the practice of adding improvised embellishments at specific points in a piece of music, is a common feature in performances of Bach's music. These embellishments may introduce small changes in onset distributions that would introduce variability. While these ornaments likely also influence the pitch distributions, they are generally diatonic and therefore should not change the mode evaluation. Despite this, relative mode is still more variable in two of three of the tools examined. While the version variability ratio is a useful metric, the exact range of these values remains unclear. While the invariant features are generally less variable than the variant features, it is unclear how extreme these values may be in a larger set of features.

## Future Directions

To maintain the benefits of the WTC discussed above while avoiding the issue of ornamentation, future evaluations with this method might use popular composers from later era's such as Mozart, Beethoven, or Chopin who have similar compositions and are widely recorded but generally do not include ornamentation. This does not account for the speed at which performers execute trills and tremolos, but careful selection of pieces may avoid that confounding variable. Further, while we focus on classical piano compositions due to the nature of the variant and invariant features in this style, the assumptions about what features are variant and invariant likely can be adapted to different styles of music.

Differences in variability between pieces indicate that structural features may have an influence on the extraction of other seemingly unrelated features. Future work will examine the effect of structural features like tempo, dynamics, articulation, and pitch height on the extraction of features that should not be influenced by these changes (i.e., chroma features and onset detection). Further, differences between versions may point to the effect of performance and audio features on seemingly unrealted features. While previous work has shown that chroma and timbre features (MFCCs) are robust to changes in audio quality, it is unclear if this extends to other features, or to manipulations in performance factors like acoustics and recording technology.

While we focus on three tools and four features here, the version variability ratio may be useful in applications outside of music. In principle, the concept of invariant and variant features is present in other domains (for instance, linguistics) making this a useful approach for evaluating non-musical feature extraction or prediction algorithms in other data types.

## Conclusion

Here we introduce a novel method for evaluating the output of music content analysis tools without relying on ground truth, while applying understanding of music perception and practice. Since these tools are used frequently both in research and industry contexts, it is important to develop frameworks for evaluating these tools to ensure that the extracted features have construct validity, and to ensure they truly measure what we think they are measuring: in the case of strictly musical features, some approximation of the human experience. In a broader sense, we aim to contribute to a rich tradition of improving the efficacy of MIR through evaluative frameworks.